### ISSUE TITLE
Clarify relationship to "django-sensible-caching"

### ISSUE THREAD

**Issue by PeterJCLaw** [lamby/django-cache-toolbox#11]
Following from #10 I discovered that there exists a fork of this project at https://github.com/lamby/django-sensible-caching/ (and https://chris-lamb.co.uk/projects/django-sensible-caching), though doesn't appear to be on PyPI.

Since this repo appears to be more advanced (certainly it's got more recent changes in it), would it be worth canonicalising around this project (repo and name) and archiving the other?

**Comment by lamby** [comment]
But isnt /this/ one (ie. django-cache-toolbox) deprecated/older? :)

**Comment by PeterJCLaw** [comment]
From what I can tell they have the same history up to 69576c923f79a3e92275d, after that they diverge (although both later remove the UPSERT behaviour which that commit merges):
- `django-cache-toolbox` has a bunch of extra changes, including switching to using pickle as the storage format, addition of tests, consistent support for `hasattr` and some other tidyps
- `django-sensible-caching`'s changes appear to only touch the `setup.py`

**Comment by lamby** [comment]
Ah, okaley, so we want to exclusively use `django-cache-toolbox` and redirect everything to that?

**Comment by PeterJCLaw** [comment]
I think so. I've only ever used `django-cache-toolbox` (I literally didn't realise that `django-sensible-caching` existed until a few days ago), so that would work for me.

I don't know who/if anyone uses `django-sensible-caching`, so I'm not well placed to comment on the relative popularity of them. That said, the GitHub network of this repo is larger than that of `django-sensible-caching`, suggesting that the majority are on this project.

**Comment by lamby** [comment]
Done!
