### ISSUE TITLE
Negative relation lookups are not cached locally

### ISSUE THREAD

**Issue by PeterJCLaw** [lamby/django-cache-toolbox#15]
Django ordinarily caches relation lookups which fail to return an instance, to avoid repeat queries within the same instance lifetime.

For example:
``` python
user = User.objects.first()
user.thing  # does a query and raises a `RelatedObjectDoesNotExist`
user.thing  # no query - raises a `RelatedObjectDoesNotExist` from the cached fail
```

However:
``` python
user = User.objects.first()
user.thing_cache  # does a query and raises a `RelatedObjectDoesNotExist`
user.thing_cache  # does another query and raises a `RelatedObjectDoesNotExist`
```

There are a couple of ways I can see to fix this, one with more side-effects which may or not be desirable.

The smaller fix would be to explicitly cache the negative lookup result locally (just as we cache the success locally) and raise appropriately.

The larger (i.e: more side-effecting) fix would be to actually use `descriptor.__get__(self)` as part of the lookup alongside or instead of `get_instance(...)`. I'm not sure what this would look like as we obviously would still want to check the remote cache first.
The side effect this has is that it would change the behaviour of the following code slightly:
```
user = User.objects.first()
user.thing_cache  # does a query, also populates user.thing
user.thing  # now doesn't do a query, where (without this change) it would have done
```
This makes it slightly easier for stale cache data to end up back in the database, though that is arguably already a risk users are taking.

I'll put up a PR for the simpler fix anyway, but would be interesting to know what you think about the other fix.

**Comment by lamby** [comment]
Great issue well explained, thanks. The other fix makes me a little nervous, particularly because whilst it might work in all our tests, Django internals could differ across time and subtly break things. Lets get the "simple" fix in first anyway. :)
