### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by PeterJCLaw** [lamby/django-cache-toolbox#19]
Just wondering if you're planning to release soon?

I realise we discussed #18 as a follow-on to #16, though I think that the bug fix/optimisation in #16 is useful on its own?

**Comment by lamby** [comment]
This was released as `1.1.1`, no? :)

**Comment by PeterJCLaw** [comment]
From the git tags I think [`1.1.1`](https://github.com/lamby/django-cache-toolbox/releases/tag/1.1.1) was before that - the history shows a couple of commits (including #16) being afterwards.
I've not checked what's in the package on PyPI though.

**Comment by lamby** [comment]
Mea culpa. I did not update my local tree. Released now as `1.2.0`...

**Comment by PeterJCLaw** [comment]
No worries, thanks for the release :)
