### ISSUE TITLE
Assumption that all cached foreign keys are primary keys

### ISSUE THREAD

**Issue by PeterJCLaw** [lamby/django-cache-toolbox#22]
At the moment there seems to be a built-in (though undocumented) assumption that any foreign key relation cached with `cache_relation` represents the primary key of the model that contains the foreign key. When this assumption is violated, cached lookups will return unexpected data.

I've put a couple of tests which explore how this can break things into a branch [`assumes-foreign-key-is-primary-key`](https://github.com/lamby/django-cache-toolbox/compare/master...PeterJCLaw:assumes-foreign-key-is-primary-key).

The issue seems to stem from the use of the current model's `pk` in the cache lookup (both the key and thus also database query) for a related model.

I can see a couple of ways to solve this:
- make `cache_relation` validate that the relation passed is the primary key on the model which contains the foreign key it's caching
- change the lookup behaviour to support non-primary-key lookups (and add checking in `cache_relation` that the relation passed is constrained to be unique)

The latter feels preferable as it would allow wider use of `cache_relation`, though it is more complicated as it would result in several cache lines potentially containing the same instance.

**Comment by lamby** [comment]
Let's at least (for now) go with checking the relation is a primary for now, to avoid people being able to use this utility in a broken manner. We can always add support for the second bit later, AIUI.
