### ISSUE TITLE
Allow custom extended User model for CacheBackedAuthenticationMiddleware

### ISSUE THREAD

**Issue by matt-dalton** [lamby/django-cache-toolbox#28]
The `CacheBackedAuthenticationMiddleware` is great, however we use a custom User model that extends `AbstractUser`. This means that when I drop the middleware in, the middleware ends up making a request to `auth-user` since fetching from the cache seems to fail.

All I have to change to get the middleware to work is to change the `middleware.py` import from `from django.contrib.auth.models import User` to `from my_project.core.models import User`.

Is there a way the lib could allow this model to be customised/overridden?

**Comment by lamby** [comment]
Could you try using https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#django.contrib.auth.get_user_model? If that works, I'll accept that PR in a second. :)

**Comment by matt-dalton** [comment]
As requested! https://github.com/lamby/django-cache-toolbox/pull/29

**Comment by lamby** [comment]
I've merged #29, so closing this. Thanks!
